// <auto-generated />
using System;
using LMS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(LMSEFCoreDbContext))]
    [Migration("20250928075319_AddNotification")]
    partial class AddNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Model.Admin.EmployeeRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employeeRegistration");
                });

            modelBuilder.Entity("LMS.Model.Company.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("LMS.Model.Company.CompanyAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("companyAdmin");
                });

            modelBuilder.Entity("LMS.Model.Company.CompanyHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("companyHoliday");
                });

            modelBuilder.Entity("LMS.Model.Leave.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("leaveApplication");
                });

            modelBuilder.Entity("LMS.Model.Leave.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalAllocatedDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalTakenDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("leaveBalance");
                });

            modelBuilder.Entity("LMS.Model.Leave.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultAllocation")
                        .HasColumnType("int");

                    b.Property<string>("GenderRestriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("leaveType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Casual Leave"
                        },
                        new
                        {
                            Id = 2,
                            AllocationFrequency = "Monthly",
                            DefaultAllocation = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Sick Leave"
                        },
                        new
                        {
                            Id = 3,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 24,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Annual Leave"
                        },
                        new
                        {
                            Id = 4,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Compensatory Leave"
                        },
                        new
                        {
                            Id = 5,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 15,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Earned Leave"
                        },
                        new
                        {
                            Id = 6,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 0,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Leave Without Pay"
                        },
                        new
                        {
                            Id = 7,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 42,
                            GenderRestriction = "Female",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Leave for miscarriage"
                        },
                        new
                        {
                            Id = 8,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 182,
                            GenderRestriction = "Female",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Maternity Leave"
                        },
                        new
                        {
                            Id = 9,
                            AllocationFrequency = "Monthly",
                            DefaultAllocation = 12,
                            GenderRestriction = "Female",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Period Leave"
                        },
                        new
                        {
                            Id = 10,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 20,
                            GenderRestriction = "Male",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Paternity Leave"
                        },
                        new
                        {
                            Id = 11,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Marriage Leave"
                        },
                        new
                        {
                            Id = 12,
                            AllocationFrequency = "Yearly",
                            DefaultAllocation = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Type = "Bereavement Leave"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
